password_randomizer function
iiitl/bash-practice-repo-24 pull request #12
Opened 2024-03-14 19:56 UTC by shibo911

added a password randomizer_function. the function takes a single argument which is the required password length.  the function creates strong passwords by using the system's randomness through /dev/urandom.
![Screenshot 2024-03-15 012537](https://github.com/iiitl/bash-practice-repo-24/assets/143445493/440e44b6-9f17-41a5-a3f3-a0a75f759fed)

2024-03-14 19:59 UTC, umeshSinghVerma commented
Hii @shibo911 kindly create a new branch with for your feature and also improve PR message

2024-03-15 09:31 UTC, rootCircle commented on scripts/password-generator
> +generate_password $1
did you meant `password_randomizer` here?

2024-03-15 09:33 UTC, rootCircle requested changes

2024-03-15 09:33 UTC, rootCircle commented on scripts/password-generator
> +    local password=$(cat /dev/urandom | tr -dc 'A-Za-z0-9!@#$%^&*()' | fold -w $length | head -n 1)
add error checking if args is empty

![image](https://github.com/iiitl/bash-practice-repo-24/assets/35325046/e2789871-62c1-4639-a20d-863c6772fc2a)

2024-03-15 09:33 UTC, rootCircle commented
@shibo911 great work! please go through the reviews right here and see to mark the relevant changes! ping me when done

2024-03-15 11:22 UTC, shibo911 commented
> @shibo911 great work! please go through the reviews right here and see to mark the relevant changes! ping me when done

@rootCircle i have made commits again and did the changes as you requested. please re-review it. thanks!

2024-03-15 12:06 UTC, rootCircle approved these changes

2024-03-15 12:09 UTC, rootCircle commented
LGTM :-) Also, one peculiar thing, the `password-generator` does not has executable permission by default! Change that by `chmod` and then commit and push.

ping me here when you're done with those, so we can move forward with your PR!

2024-03-15 14:56 UTC, rootCircle commented
Great going @shibo911! You did a great job! Thanks for your contribution! Accepted :tada:

2024-03-16 06:34 UTC, closed without merging