Adding Perms script. Solving #6
iiitl/bash-practice-repo-24 pull request #29
Opened 2024-03-15 05:41 UTC by aryamagarwal

I've written a Bash script to list the permissions of given files in octal format.
The script loops through each file to retrieve its permissions using the ls command and outputs the permissions in the specified format.

<img width="755" alt="changes#6" src="https://github.com/iiitl/bash-practice-repo-24/assets/143252449/a08d08bd-40f3-4fe6-b9a2-dc7b61b052f1">

2024-03-15 10:10 UTC, ecxtacy commented
Kindly put proper PR heading.

2024-03-15 10:40 UTC, aryamagarwal commented
Updated the PR heading.

2024-03-15 13:45 UTC, rootCircle requested changes

2024-03-15 13:45 UTC, rootCircle commented on scripts/perms
> +       if [ $ch == 'r' ]
/home/violow/FOSS/bash-practice-repo-24/scripts/perms: line 24: [: ==: unary operator expected

Your code fails running on other shells like `zsh`

Use double quotes to prevent globbing and use = instead of non-standard

https://stackoverflow.com/a/2237103

2024-03-15 13:46 UTC, rootCircle commented
Please make the required changes!

You can use linter like `shellcheck` for your help!
To install use `sudo apt install shellcheck` & for use `shellcheck file.sh`

2024-03-15 13:46 UTC, rootCircle commented
ping me here when you're done with those, so we can move forward with your PR!

2024-03-16 05:26 UTC, rootCircle approved these changes

2024-03-16 05:29 UTC, rootCircle commented
Hey @aryamagarwal! Great work on fixing those issues, I am seeing that your code simply fails to work for directory! Can you check into that?

![image](https://github.com/iiitl/bash-practice-repo-24/assets/35325046/705db16c-5a4c-4259-a9d4-c9caf616c6cf)

ping me here when you're done with those/need any help, so we can move forward with your PR!

2024-03-16 07:11 UTC, rootCircle commented
LGTM :+1: Accepted! Great work @aryamagarwal! Thanks for your contribution!

2024-03-16 07:12 UTC, closed without merging