Solved issue #1
iiitl/bash-practice-repo-24 pull request #33
Opened 2024-03-15 07:08 UTC by satyajit1206

I have written a simple Bash script that can be used on a macOS system to extract the SSID (Wi-Fi username) of the currently connected Wi-Fi network. This script utilises the airport utility that is included with macOS but is located within a framework, so its path is a bit lengthy.

2024-03-15 10:07 UTC, ecxtacy commented
Kindly write proper PR heading.

2024-03-15 14:17 UTC, rootCircle requested changes

2024-03-15 14:17 UTC, rootCircle commented on scripts/wifi-ssid
> +SSID=$(/System/Library/PrivateFrameworks/Apple80211.framework/Versions/Current/Resources/airport -I | awk '/ SSID:/ {print substr($0, index($0, $2))}')
I see you are using some MacOS specific APIs for accessing SSIDs, it is good practice to use POSIX compliant APIs like `ip` or `iw` etc. These will provide cleaner and much far more supported codes.

Please change to that

2024-03-15 14:17 UTC, rootCircle commented
ping me here when you're done with those, so we can move forward with your PR!

2024-03-16 05:31 UTC, satyajit1206 commented
@rootCircle  i have used the networksetup command which is a POSIX-compliant API on macOS instead of iw command since on macOS, there isn't a direct equivalent to the iw command found in Linux systems.

2024-03-16 06:18 UTC, rootCircle commented
> Kindly write proper PR heading.

Fix this too!

2024-03-16 06:21 UTC, rootCircle commented
> @rootCircle i have used the networksetup command which is a POSIX-compliant API on macOS instead of iw command since on macOS, there isn't a direct equivalent to the iw command found in Linux systems.

ok cool, I tested it on macOS, it works, so I can allow it!

2024-03-16 06:21 UTC, rootCircle commented
> @rootCircle i have used the networksetup command which is a POSIX-compliant API on macOS instead of iw command since on macOS, there isn't a direct equivalent to the iw command found in Linux systems.

ok cool, I tested it on macOS, it works, so I can allow it!

2024-03-16 06:21 UTC, rootCircle approved these changes

2024-03-16 06:21 UTC, rootCircle commented
ping me here when you're done with those/need any help, so we can move forward with your PR!

2024-03-16 10:27 UTC, satyajit1206 commented
@rootCircle I have changed the PR heading

2024-03-16 12:45 UTC, rootCircle commented
> @rootCircle I have changed the PR heading

cool, LGTM :+1: Thanks for your contribution!

2024-03-16 12:45 UTC, closed without merging

2024-03-16 12:46 UTC, rootCircle commented
fixes #1