feature added 'rm-gitignore'
iiitl/bash-practice-repo-24 pull request #38
Opened 2024-03-15 20:18 UTC by Sidharth-Singh10

Fixes #3 
This pull request adds a script that uses `find` to locate all Git repositories within a directory and its subdirectories. It then iterates over each repository, changing into the repository's parent directory, and running `git clean -xdf` to remove untracked files and directories.

2024-03-15 20:37 UTC, rootCircle requested changes

2024-03-15 20:37 UTC, rootCircle commented on scripts/rm-gitignore
> +    git clean -xdf
You possibly meant `git clean -Xdf` here! git clean -dfx will remove un-ignored files too!

2024-03-15 20:38 UTC, rootCircle commented
Congrats on your PR @Sidharth-Singh10, there are some changes required please go through it

ping me here when you're done with those, so we can move forward with your PR!

2024-03-15 20:50 UTC, Sidharth-Singh10 commented
@rootCircle 
Completed the requested changes.

2024-03-16 05:41 UTC, rootCircle approved these changes

2024-03-16 05:41 UTC, rootCircle commented
LGTM :+1: Accepted

2024-03-16 05:48 UTC, closed without merging